---
- name: generate heapster secret template
  template:
    src: secret.j2
    dest: "{{ mktemp.stdout }}/templates/heapster_secrets.yaml"
    force: no
  vars:
    name: heapster-secrets
    labels:
      metrics-infra: heapster
    data:
      heapster.allowed-users: >
        {{ openshift_metrics_heapster_allowed_users|b64encode }}
  when: "'secret/heapster-secrets' not in metrics_secrets.stdout_lines"
