---

- name: restart container runtime
  systemd:
    name: "{{ openshift_docker_service_name }}"
    state: restarted
    daemon_reload: yes
  register: r_docker_restart_docker_result
  until: not (r_docker_restart_docker_result is failed)
  retries: 3
  delay: 30
  when:
  - not docker_service_status_changed | default(false) | bool
  - not openshift_use_crio_only

- name: restart udev
  systemd:
    name: systemd-udevd
    state: restarted
    daemon_reload: yes
