---
r_openshift_nfs_firewall_enabled: "{{ os_firewall_enabled | default(True) }}"
r_openshift_nfs_use_firewalld: "{{ os_firewall_use_firewalld | default(False) }}"

r_openshift_nfs_os_firewall_deny: []
r_openshift_nfs_firewall_allow:
- service: nfs
  port: "2049/tcp"
