---
# these are service state handlers

# this is an example to show that handlers can be included from yaml files,
# to promote reuse between different plays or even playbooks.  They work
# just like normal handlers.

- name: restart apache
  action: service name=httpd state=restarted
- name: restart memcached
  action: service name=memcached state=restarted
