---
apiVersion: v1
kind: Role
metadata:
  name: shared-resource-viewer
  namespace: openshift
rules:
- apiGroups:
  - ""
  - template.openshift.io
  attributeRestrictions: null
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreamimages
  - imagestreams
  - imagestreamtags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - image.openshift.io
  attributeRestrictions: null
  resources:
  - imagestreams/layers
  verbs:
  - get
