---
galaxy_info:
  author: Contrail
  description: Contrail Networking
  company: Juniper Networks, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.5
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
