---
- name: Backup etcd certificates
  command: >
    tar -czvf /etc/etcd/etcd-server-certificate-backup-{{ ansible_date_time.epoch }}.tgz
    {{ etcd_ca_file }}
    {{ etcd_cert_file }}
    {{ etcd_key_file }}
    {{ etcd_peer_cert_file }}
    {{ etcd_peer_key_file }}
  args:
    warn: no
