---
builddefaults_yaml:
  BuildDefaults:
    configuration:
      apiVersion: v1
      kind: BuildDefaultsConfig
      gitHTTPProxy: "{{ openshift.builddefaults.git_http_proxy | default('', true) }}"
      gitHTTPSProxy: "{{ openshift.builddefaults.git_https_proxy | default('', true) }}"
      gitNoProxy: "{{ openshift.builddefaults.git_no_proxy | default('', true) }}"
      env:
      - name: HTTP_PROXY
        value: "{{ openshift.builddefaults.http_proxy | default('', true) }}"
      - name: HTTPS_PROXY
        value: "{{ openshift.builddefaults.https_proxy | default('', true) }}"
      - name: NO_PROXY
        value: "{{ openshift.builddefaults.no_proxy | default('', true) }}"
      - name: http_proxy
        value: "{{ openshift.builddefaults.http_proxy | default('', true) }}"
      - name: https_proxy
        value: "{{ openshift.builddefaults.https_proxy | default('', true) }}"
      - name: no_proxy
        value: "{{ openshift.builddefaults.no_proxy | default('', true) }}"
      imageLabels: "{{ openshift_builddefaults_image_labels | default(None) }}"
      nodeSelector: "{{ openshift_builddefaults_nodeselectors | default(None) }}"
      annotations: "{{ openshift_builddefaults_annotations | default(None) }}"
      resources:
        requests:
          cpu: "{{ openshift_builddefaults_resources_requests_cpu | default(None) }}"
          memory: "{{ openshift_builddefaults_resources_requests_memory | default(None) }}"
        limits:
          cpu: "{{ openshift_builddefaults_resources_limits_cpu | default(None) }}"
          memory: "{{ openshift_builddefaults_resources_limits_memory | default(None) }}"
