---
galaxy_info:
  author: Michael Hanselmann
  description: Configure project request template
  company: VSHN AG
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies:
- role: lib_utils
