---
- name: Copy node script to the node
  copy:
    src: openshift-node
    dest: /usr/local/bin/openshift-node
    mode: 0500

- name: Install cni-cleanup file
  template:
    dest: "/etc/tmpfiles.d/cleanup-cni.conf"
    src: "cleanup-cni.j2"

- name: Install Node service file
  template:
    dest: "/etc/systemd/system/{{ openshift_service_type }}-node.service"
    src: "node.service.j2"
  when: not openshift_is_atomic | bool
  notify:
  - reload systemd units
