---
container_providers:
  - connection_configurations:
      - authentication: {auth_key: "management-admin-token-here", authtype: bearer, type: AuthToken}
        endpoint: {role: default, security_protocol: ssl-without-validation, verify_ssl: 0}
    hostname: "OCP/Origin cluster hostname (providing API access)"
    name: openshift-management
    port: 8443
    type: "ManageIQ::Providers::Openshift::ContainerManager"
# Copy and update for as many OCP or Origin providers as you want to
# add to your management service
  # - connection_configurations:
  #     - authentication: {auth_key: "management-admin-token-here", authtype: bearer, type: AuthToken}
  #       endpoint: {role: default, security_protocol: ssl-without-validation, verify_ssl: 0}
  #   hostname: "OCP/Origin cluster hostname (providing API access)"
  #   name: openshift-management
  #   port: 8443
  #   type: "ManageIQ::Providers::Openshift::ContainerManager"
management_server:
  hostname: "Management server hostname (providing API access)"
  user: admin
  password: smartvm
