---
# Default behavior, you will need to ensure you run ansible with the
# -v option to see report results:

- name: Initialize facts
  import_playbook: ../../init/main.yml
  vars:
    l_init_fact_hosts: nodes:masters:etcd
    l_openshift_version_set_hosts: nodes:masters:etcd

- name: Check cert expirys
  hosts: nodes:masters:etcd
  become: yes
  roles:
    - role: openshift_certificate_expiry
