#!/bin/bash -x
#HOSTNAME=`hostname -a`
#SERVICE=`grep ^$HOSTNAME /etc/puppet/hosts.master | awk -F, '{ print $47 }'`
#ROLE=`grep ^$HOSTNAME /etc/puppet/hosts.master | awk -F, '{ print $26 }'`
#ENV=`grep ^$HOSTNAME /etc/puppet/hosts.master | awk -F, '{ print $33 }'`
#RHEL=`grep ^$HOSTNAME /etc/puppet/hosts.master | awk -F, '{ print $38 }'`
#ARCH=`grep ^$HOSTNAME /etc/puppet/hosts.master | awk -F, '{ print $39 }'`
cat <<END
---
classes:
- project_nagios
## wireless
## yum
END
exit 0
