---
- name: Update console certificates
  hosts: oo_first_master
  vars:
  roles:
  - lib_openshift
  - openshift_facts
  tasks:
  - name: Remove certificates secret
    oc_obj:
      name: console-serving-cert
      kind: secret
      state: absent
      namespace: openshift-console

  - import_role:
      name: openshift_console
