---
- name: Generate secret for efs
  template:
    src: secret.j2
    dest: "{{ mktemp.stdout }}/templates/{{ obj_name }}-secret.yaml"
  vars:
    name: efs
    obj_name: "provisioners-efs"
    labels:
      provisioners-infra: support
    secrets:
      - {key: aws-access-key-id, value: "{{openshift_provisioners_efs_aws_access_key_id}}"}
      - {key: aws-secret-access-key, value: "{{openshift_provisioners_efs_aws_secret_access_key}}"}
  check_mode: no
  changed_when: no
  when: openshift_provisioners_efs | bool
