- hosts: rhel7-wkstn.example.org
  tasks:
  - block:
    - name: include some vars
      include_vars: ../group_vars/ipaserver
    - name: install ipa automount pkgs
      yum:
        name: rpcbind,nfs-utils,autofs,ipa-client,ipa-admintools
        state: latest
    - name: configure ipa-client 
      command: "/sbin/ipa-client-install -U --principal=admin --automount-location=default --fixed-primary --force-join --domain=example.org --server=ipa.example.org --password=password --force-ntpd --enable-dns-updates"
      register: ipaclientinstall
    - debug:
        var: ipaclientinstall
      args:
        creates: /usr/sbin/ipa-client-install

- hosts: ipaserver
  tasks:
  - name: setup ipa server for client
    command: /usr/bin/ipa service-add nfs/rhel7-wkstn.example.org
    register: serviceadd
  - debug:
      var: serviceadd

- hosts: rhel7-wkstn.example.org
  tasks:
  - block:
    - name: ipa getkey
      command: "/usr/sbin/ipa-getkeytab -s {{ ipaserver }} -p nfs/{{ ansible_fqdn }} -k /etc/krb5.keytab"
      register: ipa-getkey
    - debug:
        var: ipa-getkey
      args:
        creates: /etc/krb5.keytab
      register: ipagetkey
    - name: automount
      command: /usr/sbin/ipa-client-automount --location=default
      register: ipa-client-automount
    - debug:
        var: ipa-client-automount
      
